# Generated by Django 5.2.15 on 2026-08-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('DETECTION', 'Detection'), ('SEGMENTATION', 'Segmentation'), ('MULTIMODAL', 'Multimodal'), ('NLP', 'NLP')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRAINING', 'Training'), ('FAILED', 'Failed')], default='INACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('supporting_findings', models.TextField(blank=True)),
                ('rag_context', models.TextField(blank=True)),
                ('llm_explanation', models.TextField(blank=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='cases.patientcase')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_diagnosis', models.TextField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('treatment_advice', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('doctor_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('ai_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aianalysis')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_decision', to='cases.patientcase')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
