# Generated by Django 5.2.15 on 2026-08-23 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('chief_complaint', models.TextField()),
                ('symptoms', models.TextField()),
                ('symptom_duration', models.CharField(blank=True, max_length=100)),
                ('medical_history', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('previous_diseases', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('lifestyle_info', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('TEST_REQUESTED', 'Test Requested'), ('AWAITING_REPORT', 'Awaiting Report'), ('REPORT_UPLOADED', 'Report Uploaded'), ('REPORT_VERIFIED', 'Report Verified'), ('AI_ANALYSIS', 'AI Analysis'), ('DOCTOR_REVIEW', 'Doctor Review'), ('FINAL_DECISION', 'Final Decision'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
